[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
aletheia_contract = "AvxBzjBciSWs7vjcxnXY97SDu8hYUuJXpgCeAWKN1xb5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/osman/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
